title: subhsaha
description: Blogs mostly on tech
theme: just-the-docs

url: https://subhsaha.github.io/Home

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/subhsaha/Home

