title: - subhsaha
description: Personal blogging site mosty related to tech
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Linkedin: https://www.linkedin.com/in/subhasaha92/
